#page title
page_title                                : Quacker                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

app_icon                                  : https://raw.githubusercontent.com/TheHCJ/Quacker/master/assets/icon.png                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Quacker                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Quacker is a more private and clean way to browse X

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Harley Jones                                
your_link                                 : https://thehcj.github.io                                                     
email_address                             : HarleyCJ@proton.me
github_username                           : TheHCJ
mastodon_link                             : https://defcon.social/@HCJ



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Feeds
    description                           : View your Following and For You feeds
    fontawesome_icon_name                 : newspaper
    
  - title                                 : Material You
    description                           : Looks and feels modern
    fontawesome_icon_name                 : shapes

  - title                                 : Bookmarks
    description                           : Save posts locally and offline
    fontawesome_icon_name                 : bookmark

  - title                                 : Trends
    description                           : See what's trending in the world
    fontawesome_icon_name                 : fire

  - title                                 : Light and Dark themes
    description                           : Protect your eyes
    fontawesome_icon_name                 : moon
  
  - title                                 : Subscriptions
    description                           : Follow and group accounts
    fontawesome_icon_name                 : user

  - title                                 : Polls
    description                           : View results without needing to vote
    fontawesome_icon_name                 : poll

  - title                                 : Search
    description                           : Find users and posts
    fontawesome_icon_name                 : search

  - title                                 : And more!
    fontawesome_icon_name                 : plus

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
